Feature/newcommand
armand1m-development/TropinhaNews pull request #14
Opened 2022-12-14 22:07 UTC by joaopedev

2022-12-14 22:51 UTC, armand1m requested changes

2022-12-14 22:51 UTC, armand1m commented on src/commands/climateCommands.ts
> +      const { temperature, cityName } = await getClimateValue(city || "");
nitpick:

```suggestion
      const { temperature, cityName } = await getClimateValue(city ?? "");
```

2022-12-14 22:51 UTC, armand1m commented on src/services/handleJsons.ts
> +};
major: since we'll be keeping these json files we need to setup a persistent volume for deployment

the current setup would just wipe these if the process gets recreated by whatever reason

I'll be pushing a commit into this branch to help out with this

2022-12-15 00:28 UTC, joaopedev commented on src/services/handleJsons.ts
> +};
yes sir

2023-01-07 02:32 UTC, armand1m commented on src/services/handleJsons.ts
> +export const reedJson = (way: string, content: any): Promise<boolean> => {
```suggestion
export const readJson = (way: string, content: any): Promise<boolean> => {
```

2023-01-07 19:05 UTC, closed without merging